# Generated by Django 3.2.4 on 2021-07-26 07:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='Сортировка на сайте')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coach', verbose_name='Фото')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('bith', models.CharField(blank=True, help_text='формат заполнения: 10.02.1987 г.', max_length=50, null=True, verbose_name='Дата рождения')),
                ('instagram', models.URLField(blank=True, help_text='формат заполнения: https://www.instagram.com/', max_length=300, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, help_text='формат заполнения: https://www.instagram.com/', max_length=300, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, help_text='формат заполнения: https://www.instagram.com/', max_length=300, null=True, verbose_name='Twitter')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'Тренерский штаб',
                'ordering': ['ordernumber'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='Сортировка на сайте')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
            ],
            options={
                'verbose_name': 'часто задаваемый вопрос',
                'verbose_name_plural': 'часто задаваемые вопросы',
                'ordering': ['ordernumber'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='Телефон')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения')),
            ],
            options={
                'verbose_name': 'форма обратной связи',
                'verbose_name_plural': 'формы обратной связи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('name', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'история клуба',
                'verbose_name_plural': 'история клуба',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d', verbose_name='Картинка')),
                ('content_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Статья')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
                ('head', models.BooleanField(default=False, verbose_name='Разместить в шапке')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='Сортировка на сайте')),
                ('image', models.ImageField(blank=True, default='', upload_to='schedule', verbose_name='Картинка')),
                ('years', models.CharField(max_length=150, verbose_name='Заголовок/года рождения')),
                ('district', models.CharField(max_length=150, verbose_name='Район')),
                ('address', models.CharField(max_length=350, verbose_name='Адрес')),
                ('schedule', models.CharField(max_length=350, verbose_name='Расписание занятий')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('contact', models.CharField(max_length=350, verbose_name='ФИО')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
            ],
            options={
                'verbose_name': 'расписание тренировок',
                'verbose_name_plural': 'расписания тренировок',
                'ordering': ['ordernumber'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='Сортировка на сайте')),
                ('name', models.CharField(max_length=150, verbose_name='Название компании')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsor', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('active', models.BooleanField(default=False, verbose_name='Активно на сайте')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнеры',
                'ordering': ['ordernumber'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='Вход')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Выход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'посещение сайта пользователями',
                'verbose_name_plural': 'посещение сайта пользователями',
            },
        ),
    ]
